#!/usr/bin/env bash
# Configuring SSL termination and certificates

frontend my_frontend
        bind *:80
        bind *:443 ssl crt /etc/letsencrypt/live/www.byteangel.tech/all.pem
        http-request set-header X-Forwaded-Proto https
        default_backend my_backend

backend my_backend
        balance roundrobin
        server 530351-web-01 54.237.48.155:80 check
        server 530351-web-02 18.233.62.142:80 check
