#!/usr/bin/env bash
# Configuring SSL termination and certificates

frontend my_frontend
        mode http
        bind -- *:80
        bind -- *:443 ssl crt /etc/letsencrypt/live/www.byteangel.tech/all.pem
        http-request redirect scheme https unless \{ ssl_fc \}
        http-request set-header X-Forwarded-Proto https if \{ ssl_fc \}
        http-request set-header X-Forwarded-Proto http if \! \{ ssl_fc \}
        default_backend my_backend


backend my_backend
        mode http
        balance roundrobin
        server 530351-web-01 54.237.48.155:80 check
        server 530351-web-02 18.233.62.142:80 check
